# Generated by Django 3.2.5 on 2021-08-03 10:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Room',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
    ]
